From Literal Value
==================
kubectl create configmap cus-conf --from-literal=KEY1=Value1 --from-literal=KEY2=Value2

apiVersion: v1
kind: Pod
metadata:
 name: configmap-demo-pod
spec:
 containers:
 - name: demo
 image: alpine
 command: ["sleep", "3600"]
 env:
 - name: ENV_VAL_1
     valueFrom:
       configMapKeyRef:
         name: cus-conf
         key: KEY1
 - name: ENV_VAL_2
     valueFrom:
       configMapKeyRef:
         name: cus-con
  volumeMounts:
    - name: kishore
      mountPath: /opt
  volumes:
  - name: kishore
    configMap:
      name: cus-conf
      readOnly: true
   
  

From file
=========
kubectl create configmap cus-conf --from-file=/path/to/config-map.txt
kubectl create configmap cus-conf --from-file=/path/to/Directory

Config Map Declarative Way
==========================

---
apiVersion: v1
kind: ConfigMap
metadata:
 name: game-demo
data:
 KEY1: "VALUE1"
 KEY2: "VALUE2"
 KEY3: "VALUE3"
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: nginx-conf
data:
 nginx.conf: |
   user nginx;
   worker_processes 1;
   events {
     worker_connections 10240;
   }
   http {
     server {
       listen 80;
       server_name localhost;
       location / {
         root /usr/share/nginx/html; #Change this line
         index index.html index.htm;
       }
     }
   }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bridge-conf
data:
  file.txt: |
    {"kishore" : "2WjY9+CATeSWBaQxkGbjCA==:Srn0mAfMh58j6Zl38LGm76JJF66c9Y5pl0V3"}

 ---

apiVersion: v1
kind: Secret
metadata:
  name: tableau-secret
data:
  file.txt: |-
    eyJraXNob3JlIiA6ICIyV2pZOStDQVRlU1dCYVF4a0diakNBPT06U3JuMG1BZk1oNThqNlpsMzhMR203NkpKRjY2YzlZNXAifQ3V0l==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tableau-bridge
  labels:
    app: bridge
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: bridge
  template:
    metadata:
      labels:
        app: bridge
    spec:
      volumes:
      - name: kishore
        secret:
          secretName: tableau-secret
      containers:
      - name: tableau-bridge
        image: krishnakishore27/tableau-bridge:latest
        ports:
        - containerPort: 80
        command: ['sh', '-c', '/opt/tableau/tableau_bridge/bin/TabBridgeClientWorker -e --patTokenId="kishore" --userEmail="krishnakishore.reddy@salesforce.com" --client="Kishorek8sSecretAgent" --site="krishnakishorereddy" --patTokenFile="/mnt/file.txt" --poolId="dc372dc4-801e-4025-b98e-a83051e4884d" && tail -f /dev/null ']
        volumeMounts:
        - name: kishore
          mountPath: /mnt

