apiVersion: v1
kind: Pod 
metadata:
  name: nginx-volume
  labels:
    app: nginx
spec:
  volumes:
  - name: nginxvolume
    hostPath:
      path: /opt/nginx
      type: Directory
  containers: 
    name: nginx-pod
    image: nginx 
    volumeMounts:
      - name:  nginxvolume
        mountPath: /opt

