apiVersion: v1
kind: Pod 
metadata:
  name: nginx-volume
  labels:
    app: nginx
spec:
  volumes:
  - name: nginxvolume
    hostPath:
      path: /opt/nginx
      type: Directory
  containers: 
    name: nginx-pod
    image: nginx 
    volumeMounts:
      - name:  nginxvolume
        mountPath: /opt

---
apiVersion: v1
kind: Pod
metadata:
  name: emptydir
  labels:
    app: nginx
spec:
  volumes:
  - name: emptydir
    emptyDir: {]
  containers:
  - name: nginx-emptydir
    image: nginx:latest
    command: ['/bin/bash']
    args: ['-c', 'echo "Hola"']
    volumeMounts:
    - name: emptydir
      mountPath: /usr/share/nginx/html
